### ISSUE TITLE
Clean up vite-project

### ISSUE THREAD

**Issue by chrillah** [PhilipSamuelsson/Labb-3-Team-6-#2]
Clean up vite, remove all unnecessary stuff

**Comment by chrillah** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up VITE](https://trello.com/c/2G07vf2s/13-clean-up-vite)

**Comment by axxcident** [comment]
Stänger detta issue med min auktoritet som Scrum Master. Bra jobbat.
